"""empty message

Revision ID: 597b6f2b3c27
Revises: 958038e99d25
Create Date: 2025-05-29 23:07:44.997828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597b6f2b3c27'
down_revision = '958038e99d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
